#ifndef CONFIG_COLOR_H
#define CONFIG_COLOR_H

#include <SDL3/SDL.h>

#define EMPTY_COLOR_BASE_R 0
#define EMPTY_COLOR_BASE_G 0
#define EMPTY_COLOR_BASE_B 0
#define EMPTY_COLOR_BASE_A 255
#define EMPTY_COLOR_VARIATION 0

#define SAND_COLOR_BASE_R 245
#define SAND_COLOR_BASE_G 227
#define SAND_COLOR_BASE_B 66
#define SAND_COLOR_BASE_A 255
#define SAND_COLOR_VARIATION 12

#define ROCK_COLOR_BASE_R 55
#define ROCK_COLOR_BASE_G 55
#define ROCK_COLOR_BASE_B 55
#define ROCK_COLOR_BASE_A 255
#define ROCK_COLOR_VARIATION 6

#define BASE_COLOR(TYPE) (SDL_Color){TYPE##_COLOR_BASE_R, TYPE##_COLOR_BASE_G, TYPE##_COLOR_BASE_B, TYPE##_COLOR_BASE_A}

#define EMPTY_BASE_COLOR BASE_COLOR(EMPTY)
#define SAND_BASE_COLOR BASE_COLOR(SAND)
#define ROCK_BASE_COLOR BASE_COLOR(ROCK)

#endif