#ifndef CONFIG_SIMULATION_H
#define CONFIG_SIMULATION_H

#include "display_config.h"

/* PARTICLE */
#define PARTICLE_SIZE 5

/* GRID */
#define GRID_WIDTH (DISPLAY_WIDTH / PARTICLE_SIZE)
#define GRID_HEIGHT (DISPLAY_HEIGHT / PARTICLE_SIZE)

/* SIMULATION */
#define SIMULATION_TICKS_PER_SECOND 60
#define SIMULATION_TICK_RATE (1.0 / SIMULATION_TICKS_PER_SECOND)

/* BRUSH */
#define DEFAULT_BRUSH_RADIUS 2
#define MIN_BRUSH_RADIUS 0
#define MAX_BRUSH_RADIUS 20

#endif