#ifndef CONFIG_H
#define CONFIG_H

#define DISPLAY_TITLE "Falling Sand"
#define DISPLAY_WIDTH 1280
#define DISPLAY_HEIGHT 720
#define DISPLAY_WINDOW_FLAGS SDL_WINDOW_BORDERLESS
#define DISPLAY_INIT_FLAGS SDL_INIT_VIDEO
#define DISPLAY_LOGICAL_PRESENTATION SDL_LOGICAL_PRESENTATION_LETTERBOX

#endif
