#ifndef FALLING_SAND_CONFIG_H
#define FALLING_SAND_CONFIG_H

#include <SDL3/SDL.h>

/* DISPLAY */
#define DISPLAY_TITLE "Falling Sand"
#define DISPLAY_WIDTH 1280
#define DISPLAY_HEIGHT 720
#define DISPLAY_WINDOW_FLAGS SDL_WINDOW_BORDERLESS
#define DISPLAY_INIT_FLAGS SDL_INIT_VIDEO
#define DISPLAY_LOGICAL_PRESENTATION SDL_LOGICAL_PRESENTATION_LETTERBOX

/* PARTICLE */
#define PARTICLE_SIZE 5

/* GRID */
#define GRID_WIDTH (DISPLAY_WIDTH / PARTICLE_SIZE)
#define GRID_HEIGHT (DISPLAY_HEIGHT / PARTICLE_SIZE)

/* COLOR */
#define EMPTY_COLOR_BASE_R 0
#define EMPTY_COLOR_BASE_G 0
#define EMPTY_COLOR_BASE_B 0
#define EMPTY_COLOR_BASE_A 255
#define EMPTY_COLOR_VARIATION 0

#define SAND_COLOR_BASE_R 245
#define SAND_COLOR_BASE_G 227
#define SAND_COLOR_BASE_B 66
#define SAND_COLOR_BASE_A 255
#define SAND_COLOR_VARIATION 12

#define ROCK_COLOR_BASE_R 55
#define ROCK_COLOR_BASE_G 55
#define ROCK_COLOR_BASE_B 55
#define ROCK_COLOR_BASE_A 255
#define ROCK_COLOR_VARIATION 6

#define COLOR_EMPTY (SDL_Color){ .r = EMPTY_COLOR_BASE_R, .g = EMPTY_COLOR_BASE_G, .b = EMPTY_COLOR_BASE_B, .a = EMPTY_COLOR_BASE_A }
#define COLOR_SAND (SDL_Color){ .r = SAND_COLOR_BASE_R, .g = SAND_COLOR_BASE_G, .b = SAND_COLOR_BASE_B, .a = SAND_COLOR_BASE_A }
#define COLOR_ROCK (SDL_Color){ .r = ROCK_COLOR_BASE_R, .g = ROCK_COLOR_BASE_G, .b = ROCK_COLOR_BASE_B, .a = ROCK_COLOR_BASE_A }

#endif
